# Generated by Django 3.0.6 on 2023-08-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_valid',
        ),
    ]
