# Generated by Django 3.0.6 on 2023-08-07 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Project Name')),
                ('type', models.CharField(choices=[('Web', 'Web'), ('App', 'App'), ('Pc', 'Pc'), ('MiniProgram', 'MiniProgram')], default='Web', max_length=50, verbose_name='Project Type')),
                ('private', models.CharField(choices=[(0, 0), (1, 1)], default=0, max_length=50, verbose_name='Project private')),
                ('avatar', models.ImageField(blank=True, default='avatar/default.png', null=True, upload_to='avatar/', verbose_name='Project Avatar')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Project Desc')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Project CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Project UpdateTime')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
                'ordering': ('-create_time',),
            },
        ),
    ]
