# Generated by Django 3.0.6 on 2023-08-11 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projectrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrole',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectrole',
            old_name='user_id',
            new_name='user',
        ),
    ]
