# Generated by Django 3.0.6 on 2023-09-12 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230811_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='api.Project', verbose_name='Project'),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', models.TextField(default=[], verbose_name='Relation Tree')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
            ],
            options={
                'verbose_name': 'Relation',
                'verbose_name_plural': 'Relation',
            },
        ),
    ]
