# Generated by Django 3.0.6 on 2023-09-12 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230912_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address Name')),
                ('host', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Host')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Address CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Address UpdateTime')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='TestEnvironment Name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='TestEnvironment Desc')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='TestEnvironment CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='TestEnvironment UpdateTime')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Test Environment',
                'verbose_name_plural': 'Test Environment',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Api Name')),
                ('request_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Api RequestMethod')),
                ('url', models.TextField(verbose_name='Api Url')),
                ('request_headers', models.TextField(verbose_name='Api RequestHeaders')),
                ('body_type', models.CharField(choices=[('none', 'none'), ('json', 'json'), ('data', 'data')], default='json', max_length=50, verbose_name='Api BodyType')),
                ('params', models.TextField(verbose_name='Api Params')),
                ('body', models.TextField(verbose_name='Api Body')),
                ('directory_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Api DirectoryId')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Api CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Api UpdateTime')),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Address', verbose_name='Api Gateway')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_creator', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Api',
                'verbose_name_plural': 'Api',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='env',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TestEnvironment', verbose_name='Address Env'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_creator', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
