# Generated by Django 3.0.6 on 2023-09-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230912_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='body',
        ),
        migrations.RemoveField(
            model_name='api',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='api',
            name='request_headers',
        ),
        migrations.RemoveField(
            model_name='api',
            name='request_method',
        ),
        migrations.AddField(
            model_name='api',
            name='data',
            field=models.TextField(default=None, verbose_name='Api Data'),
        ),
        migrations.AddField(
            model_name='api',
            name='extract',
            field=models.TextField(default=None, verbose_name='Api Extract'),
        ),
        migrations.AddField(
            model_name='api',
            name='headers',
            field=models.TextField(default=None, verbose_name='Api Headers'),
        ),
        migrations.AddField(
            model_name='api',
            name='hooks',
            field=models.TextField(default=None, verbose_name='Api Hooks'),
        ),
        migrations.AddField(
            model_name='api',
            name='json',
            field=models.TextField(default=None, verbose_name='Api Json'),
        ),
        migrations.AddField(
            model_name='api',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Api Method'),
        ),
        migrations.AddField(
            model_name='api',
            name='validate',
            field=models.TextField(default=None, verbose_name='Api Validate'),
        ),
        migrations.AlterField(
            model_name='api',
            name='params',
            field=models.TextField(default=None, verbose_name='Api Params'),
        ),
        migrations.AlterField(
            model_name='api',
            name='url',
            field=models.TextField(default=None, verbose_name='Api Url'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', null=True, upload_to='avatar/', verbose_name='User Avatar'),
        ),
    ]
