# Generated by Django 3.0.6 on 2023-12-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20231124_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='api',
            name='data',
        ),
        migrations.RemoveField(
            model_name='api',
            name='json',
        ),
        migrations.RemoveField(
            model_name='api',
            name='params',
        ),
        migrations.AddField(
            model_name='api',
            name='raw',
            field=models.TextField(default=None, verbose_name='Api Raw'),
        ),
    ]
