# Generated by Django 4.2 on 2024-04-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_datasource_database_alter_datasource_port_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasource",
            name="name",
        ),
        migrations.AlterField(
            model_name="datasource",
            name="database",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="DataSource Name"
            ),
        ),
    ]
