# Generated by Django 4.2 on 2023-12-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_address_id_alter_api_id_alter_project_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoAdminAccessIPWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'DjangoAdminAccessIPWhitelist',
                'verbose_name_plural': 'DjangoAdminAccessIPWhitelist',
                'db_table': 'django_admin_access_ip_whitelist',
                'permissions': (('can_whitelist_user', 'Can Whitelist User'),),
            },
        ),
    ]
