# Generated by Django 4.2 on 2023-12-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_djangoadminaccessipwhitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoadminaccessipwhitelist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
