# Generated by Django 4.2 on 2023-12-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_djangoadminaccessipwhitelist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoadminaccessipwhitelist',
            name='name',
            field=models.CharField(blank=True, help_text='Enter username to whitelist', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='djangoadminaccessipwhitelist',
            name='whitelist_reason',
            field=models.CharField(blank=True, help_text='Reason for the whitelist?', max_length=255, null=True),
        ),
    ]
