# Generated by Django 4.2 on 2024-04-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_api_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api",
            name="method",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Api Method"
            ),
        ),
        migrations.AlterField(
            model_name="api",
            name="name",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Api Name"
            ),
        ),
    ]
