# Generated by Django 4.2 on 2023-12-21 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_api_tags_api_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Case Name')),
                ('directory_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Case DirectoryId')),
                ('priority', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0, max_length=50, verbose_name='Case Priority')),
                ('rerun', models.CharField(blank=True, max_length=50, null=True, verbose_name='Case Name')),
                ('threads', models.CharField(blank=True, max_length=50, null=True, verbose_name='Case Name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Case Desc')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Case CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Case UpdateTime')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('step', models.ManyToManyField(to='api.api')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_creator', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Case',
            },
        ),
    ]
