# Generated by Django 4.2 on 2024-01-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_case_step_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='case',
        ),
    ]
