# Generated by Django 4.2 on 2024-01-03 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_step_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step', to='api.case', verbose_name='Step Case'),
        ),
    ]
