# Generated by Django 4.2 on 2024-01-18 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_step_case"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Plan Name"
                    ),
                ),
                ("cron", models.TextField(default=None, verbose_name="Plan Cron")),
                (
                    "priority",
                    models.CharField(
                        choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)],
                        default=0,
                        max_length=50,
                        verbose_name="Plan Priority",
                    ),
                ),
                (
                    "case_list",
                    models.TextField(default=None, verbose_name="Plan CaseList"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[(0, 0), (1, 1)],
                        default=0,
                        max_length=50,
                        verbose_name="Plan State",
                    ),
                ),
                (
                    "pass_rate",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Plan PassRate",
                    ),
                ),
                (
                    "msg_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Plan MsgType",
                    ),
                ),
                (
                    "receiver",
                    models.TextField(default=None, verbose_name="Plan Receiver"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Plan CreateTime"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Plan UpdateTime"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Step",
                "verbose_name_plural": "Step",
            },
        ),
    ]
