# Generated by Django 4.2 on 2024-01-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
