# Generated by Django 4.2 on 2024-01-29 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_plan_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiCopy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ApiCopy Name",
                    ),
                ),
                (
                    "directory_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ApiCopy DirectoryId",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ApiCopy Method",
                    ),
                ),
                ("url", models.TextField(default=None, verbose_name="Api Url")),
                (
                    "priority",
                    models.CharField(
                        choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)],
                        default=0,
                        max_length=50,
                        verbose_name="ApiCopy Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[(0, 0), (1, 1), (2, 2)],
                        default=0,
                        max_length=50,
                        verbose_name="ApiCopy Status",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True, null=True, verbose_name="ApiCopy Desc"
                    ),
                ),
                (
                    "headers",
                    models.TextField(default=None, verbose_name="ApiCopy Headers"),
                ),
                (
                    "params",
                    models.TextField(default=None, verbose_name="ApiCopy Params"),
                ),
                ("raw", models.TextField(default=None, verbose_name="ApiCopy raw")),
                (
                    "setup_script",
                    models.TextField(default=None, verbose_name="ApiCopy SetupScript"),
                ),
                (
                    "teardown_script",
                    models.TextField(
                        default=None, verbose_name="ApiCopy TeardownScript"
                    ),
                ),
                (
                    "validate",
                    models.TextField(default=None, verbose_name="ApiCopy Validate"),
                ),
                (
                    "extract",
                    models.TextField(default=None, verbose_name="ApiCopy Extract"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ApiCopy CreateTime"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="ApiCopy UpdateTime"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apiCopy_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "ApiCopy",
                "verbose_name_plural": "ApiCopy",
            },
        ),
    ]
