# Generated by Django 4.2 on 2024-04-22 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_remove_testenvironment_host_testenvironment_server"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Notice Name"
                    ),
                ),
                (
                    "msg_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Notice MsgType",
                    ),
                ),
                (
                    "url",
                    models.TextField(blank=True, null=True, verbose_name="Notice Url"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Notice CreateTime"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Notice UpdateTime"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notice_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notice",
                        to="api.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notice",
                "verbose_name_plural": "Notice",
                "ordering": ("-create_time",),
            },
        ),
    ]
