# Generated by Django 5.0.4 on 2024-04-28 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_remove_notice_project_notice_trigger_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataStructure",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="DataStructure Name",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True, null=True, verbose_name="DataStructure Desc"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (0, "None"),
                            (1, "Form Data"),
                            (2, "X Www Form Urlencoded"),
                            (3, "Raw"),
                        ],
                        default=0,
                        max_length=50,
                        verbose_name="DataStructure Type",
                    ),
                ),
                (
                    "raw",
                    models.TextField(default=None, verbose_name="DataStructure raw"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="DataStructure CreateTime"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="DataStructure UpdateTime"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datastructure_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "ApiCopy",
                "verbose_name_plural": "ApiCopy",
            },
        ),
    ]
