# Generated by Django 5.0.4 on 2024-05-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_menu_hidden"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectrole",
            options={
                "verbose_name": "ProjectRole",
                "verbose_name_plural": "ProjectRole",
            },
        ),
    ]
