# Generated by Django 5.0.4 on 2024-05-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_delete_tasklog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApschedulerJobs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "job_state",
                    models.TextField(
                        default=None, verbose_name="ApschedulerJobs JobState"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="ApschedulerJobs Status",
                    ),
                ),
                (
                    "is_error",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ApschedulerJobs IsError"
                    ),
                ),
                (
                    "error_msg",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="ApschedulerJobs ErrorMsg",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="ApschedulerJobs Trigger",
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="ApschedulerJobs Desc",
                    ),
                ),
                (
                    "next_run_time",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="ApschedulerJobs NextRunTime",
                    ),
                ),
                (
                    "run_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ApschedulerJobs RunTime"
                    ),
                ),
            ],
            options={
                "verbose_name": "ApschedulerJobs",
                "verbose_name_plural": "ApschedulerJobs",
            },
        ),
    ]
