# Generated by Django 5.0.4 on 2024-06-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_alter_closedtasksdetail_err_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="closedtasksdetail",
            name="err_type",
            field=models.CharField(
                choices=[
                    ("系统异常", "System Err"),
                    ("用例错误", "Case Err"),
                    ("环境异常", "Environ Err"),
                    ("断言错误", "Assert Err"),
                ],
                max_length=50,
                null=True,
                verbose_name="ClosedTasksDetail ErrType",
            ),
        ),
    ]
