

class NoticeType:

    WEBHOOK = "WEBHOOK"
    DINGDING = "DINGDING"
    WEIXIN = "WEIXIN"
    FEISHU = "FEISHU"


class NoticeEvents:

    COMPLETED = "TEST_CASE_COMPLETED"
    COMPLETED_WITH_FAILURE = "TEST_CASE_COMPLETED_WITH_FAILURE"
