# Generated by Django 4.2 on 2024-02-06 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_case_djangoadminaccessipwhitelist_project_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={"verbose_name": "Plan", "verbose_name_plural": "Plan"},
        ),
    ]
