# Generated by Django 4.2 on 2024-02-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_detail_main_detailstep_detail_case"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detail",
            old_name="case",
            new_name="report",
        ),
        migrations.RenameField(
            model_name="detailstep",
            old_name="case",
            new_name="detail",
        ),
    ]
