# Generated by Django 4.2 on 2024-02-07 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_case_detail_report_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailstep",
            name="detail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="steps",
                to="api.detail",
                verbose_name="DetailStep Step",
            ),
        ),
    ]
