# Generated by Django 4.2 on 2024-02-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_detailstep_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailstep",
            name="sort",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="DetailStep sort"
            ),
        ),
    ]
