# Generated by Django 4.2 on 2024-04-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_datasource"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="database",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="DataSource Database",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="port",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="DataSource Port"
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="user",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="DataSource User"
            ),
        ),
    ]
