# Generated by Django 4.2 on 2024-04-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_functions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="functions",
            options={
                "ordering": ("-create_time",),
                "verbose_name": "Functions",
                "verbose_name_plural": "Functions",
            },
        ),
    ]
