# Generated by Django 4.2 on 2024-04-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_functions_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="headers",
            field=models.TextField(
                blank=True, null=True, verbose_name="Address Headers"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="variables",
            field=models.TextField(
                blank=True, null=True, verbose_name="Address Variables"
            ),
        ),
    ]
