# Generated by Django 4.2 on 2024-04-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_tasklog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="C:\\Users\\86135\\Desktop\\EasyPost\\UNIT-BACKEND\\api\\templates\\media\\default.png",
                null=True,
                upload_to="C:\\Users\\86135\\Desktop\\EasyPost\\UNIT-BACKEND\\api\\templates\\media",
                verbose_name="Project Avatar",
            ),
        ),
    ]
