# Generated by Django 4.2 on 2024-04-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_api_method_alter_api_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="source",
            field=models.TextField(default=None, verbose_name="Api Source"),
        ),
    ]
