# Generated by Django 4.2 on 2024-04-12 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_api_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="VerifyCode AddTime"
            ),
        ),
    ]
