# Generated by Django 4.2 on 2024-04-12 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_user_last_login_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ip_address",
            field=models.CharField(
                max_length=125, null=True, verbose_name="User IpAddress"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="User LastLoginTime"
            ),
        ),
    ]
