# Generated by Django 4.2 on 2024-04-17 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_user_ip_address_alter_user_last_login_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testenvironment",
            old_name="desc",
            new_name="remarks",
        ),
        migrations.AddField(
            model_name="datasource",
            name="env",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="env",
                to="api.testenvironment",
                verbose_name="DataSource env",
            ),
        ),
        migrations.AddField(
            model_name="testenvironment",
            name="headers",
            field=models.TextField(
                blank=True, null=True, verbose_name="Address Headers"
            ),
        ),
        migrations.AddField(
            model_name="testenvironment",
            name="host",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="TestEnvironment Host",
            ),
        ),
        migrations.AddField(
            model_name="testenvironment",
            name="variables",
            field=models.TextField(
                blank=True, null=True, verbose_name="TestEnvironment Variables"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="C:\\Users\\86135\\Desktop\\EasyPost\\unit-backend\\api\\templates\\media\\default.png",
                null=True,
                upload_to="C:\\Users\\86135\\Desktop\\EasyPost\\unit-backend\\api\\templates\\media",
                verbose_name="User Avatar",
            ),
        ),
    ]
