# Generated by Django 4.2 on 2024-04-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_rename_desc_testenvironment_remarks_datasource_env_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="env",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_source",
                to="api.testenvironment",
                verbose_name="DataSource env",
            ),
        ),
    ]
