# Generated by Django 4.2 on 2024-04-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_remove_datasource_env_binddatasource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binddatasource",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="BindDataSource CreateTime"
            ),
        ),
        migrations.AlterField(
            model_name="binddatasource",
            name="database",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="BindDataSource Name"
            ),
        ),
        migrations.AlterField(
            model_name="binddatasource",
            name="env",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_source",
                to="api.testenvironment",
                verbose_name="BindDataSource env",
            ),
        ),
        migrations.AlterField(
            model_name="binddatasource",
            name="host",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="BindDataSource Host",
            ),
        ),
        migrations.AlterField(
            model_name="binddatasource",
            name="password",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="BindDataSource Host",
            ),
        ),
        migrations.AlterField(
            model_name="binddatasource",
            name="port",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="BindDataSource Port",
            ),
        ),
        migrations.AlterField(
            model_name="binddatasource",
            name="update_time",
            field=models.DateTimeField(
                auto_now=True, verbose_name="BindDataSource UpdateTime"
            ),
        ),
        migrations.AlterField(
            model_name="binddatasource",
            name="user",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="BindDataSource User",
            ),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
