# Generated by Django 4.2 on 2024-04-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_binddatasource_create_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testenvironment",
            name="host",
        ),
        migrations.AddField(
            model_name="testenvironment",
            name="server",
            field=models.TextField(
                blank=True, null=True, verbose_name="TestEnvironment Server"
            ),
        ),
    ]
