# Generated by Django 4.2 on 2024-04-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_notice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notice",
            name="project",
        ),
        migrations.AddField(
            model_name="notice",
            name="trigger_events",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notice TriggerEvent"
            ),
        ),
    ]
