# Generated by Django 5.0.4 on 2024-05-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_projectrole_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api",
            name="priority",
            field=models.CharField(
                choices=[(0, "P0"), (1, "P1"), (2, "P2"), (3, "P3"), (4, "P4")],
                default=0,
                max_length=50,
                verbose_name="Api Priority",
            ),
        ),
        migrations.AlterField(
            model_name="api",
            name="status",
            field=models.CharField(
                choices=[(0, "Debugging"), (1, "Obsoleted"), (2, "Normal")],
                default=0,
                max_length=50,
                verbose_name="Api Status",
            ),
        ),
        migrations.AlterField(
            model_name="apicopy",
            name="priority",
            field=models.CharField(
                choices=[(0, "P0"), (1, "P1"), (2, "P2"), (3, "P3"), (4, "P4")],
                default=0,
                max_length=50,
                verbose_name="ApiCopy Priority",
            ),
        ),
        migrations.AlterField(
            model_name="apicopy",
            name="status",
            field=models.CharField(
                choices=[(0, "Debugging"), (1, "Obsoleted"), (2, "Normal")],
                default=0,
                max_length=50,
                verbose_name="ApiCopy Status",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="priority",
            field=models.CharField(
                choices=[(0, "P0"), (1, "P1"), (2, "P2"), (3, "P3"), (4, "P4")],
                default=0,
                max_length=50,
                verbose_name="Case Priority",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="priority",
            field=models.CharField(
                choices=[(0, "P0"), (1, "P1"), (2, "P2"), (3, "P3"), (4, "P4")],
                default=0,
                max_length=50,
                verbose_name="Plan Priority",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="state",
            field=models.CharField(
                choices=[(0, "Stop"), (1, "Running")],
                default=0,
                max_length=50,
                verbose_name="Plan State",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="private",
            field=models.CharField(
                choices=[(0, "Public"), (1, "Private")],
                default=0,
                max_length=50,
                verbose_name="Project private",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("Web", "Web"),
                    ("App", "App"),
                    ("Pc", "Pc"),
                    ("MiniProgram", "Miniprogram"),
                ],
                default="Web",
                max_length=50,
                verbose_name="Project Type",
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="type",
            field=models.CharField(
                choices=[(0, "Api"), (1, "Case")],
                default=0,
                max_length=50,
                verbose_name="Relation Type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=6,
                verbose_name="User Gender",
            ),
        ),
        migrations.AlterField(
            model_name="verifycode",
            name="account_type",
            field=models.CharField(
                choices=[("email", "Email"), ("mobile", "Mobile")],
                default="email",
                max_length=6,
                verbose_name="VerifyCode AccountType",
            ),
        ),
    ]
