# Generated by Django 5.0.4 on 2024-05-17 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_alter_api_priority_alter_api_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="UserRoleId"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="UserRoleId"
                    ),
                ),
                (
                    "is_super",
                    models.BooleanField(default=False, verbose_name="UserRoleIsSuper"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "UserRole",
                "verbose_name_plural": "UserRole",
            },
        ),
    ]
