# Generated by Django 5.0.4 on 2024-05-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_userrole_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskLog",
        ),
    ]
