# Generated by Django 5.0.4 on 2024-05-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_apschedulerjobs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apschedulerjobs",
            options={"managed": False},
        ),
    ]
