# Generated by Django 5.0.4 on 2024-06-20 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_datastructure_options_project_test_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosedTasks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="ClosedTasks Name",
                    ),
                ),
                (
                    "runnability",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="ClosedTasks Runnability",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[(0, "Open"), (1, "Closed")],
                        default=0,
                        max_length=50,
                        verbose_name="ClosedTasks State",
                    ),
                ),
                (
                    "detail",
                    models.TextField(default=[], verbose_name="ClosedTasks Detail"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ClosedTasks CreateTime"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="ClosedTasks UpdateTime"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "ClosedTasks",
                "verbose_name_plural": "ClosedTasks",
            },
        ),
    ]
