# Generated by Django 5.0.4 on 2024-06-20 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_closedtasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="closedtasks",
            name="project",
        ),
    ]
