# Generated by Django 5.0.4 on 2024-06-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_remove_project_test_type_closedtasks_test_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="closedtasks",
            name="test_type",
            field=models.CharField(
                choices=[("UI自动化", "Ui"), ("API自动化", "Api")],
                default="API自动化",
                max_length=50,
                verbose_name="ClosedTasks TestType",
            ),
        ),
    ]
