# Generated by Django 5.0.4 on 2024-06-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_alter_closedtasksdetail_err_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="closedtasksdetail",
            name="err_msg",
            field=models.TextField(default="", verbose_name="ClosedTasksDetail ErrMsg"),
        ),
    ]
