# Generated by Django 5.0.4 on 2024-06-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_closedtasksdetail_err_msg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="closedtasksdetail",
            name="err_msg",
        ),
    ]
