# Generated by Django 5.0.4 on 2024-06-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_remove_closedtasksdetail_err_msg"),
    ]

    operations = [
        migrations.AddField(
            model_name="closedtasksdetail",
            name="err_msg",
            field=models.TextField(default="", verbose_name="ClosedTasksDetail ErrMsg"),
        ),
        migrations.AddField(
            model_name="closedtasksdetail",
            name="err_png",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="ClosedTasksDetail ErrPng",
            ),
        ),
    ]
