# Generated by Django 5.0.4 on 2024-07-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_closedtasksdetail_err_msg_closedtasksdetail_err_png"),
    ]

    operations = [
        migrations.AlterField(
            model_name="closedtasksdetail",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
