# Generated by Django 5.0.4 on 2024-09-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_remove_api_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="priority",
            field=models.CharField(
                choices=[(0, "P0"), (1, "P1"), (2, "P2"), (3, "P3"), (4, "P4")],
                default=0,
                max_length=50,
                verbose_name="Step Priority",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="status",
            field=models.CharField(
                choices=[(0, "Debugging"), (1, "Obsoleted"), (2, "Normal")],
                default=0,
                max_length=50,
                verbose_name="Step Status",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatar/default.png",
                null=True,
                upload_to="C:\\Users\\86135\\Desktop\\EasyPost\\unit-backend\\api\\templates\\media",
                verbose_name="Project Avatar",
            ),
        ),
    ]
