# Generated by Django 5.0.4 on 2024-11-05 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_alter_plan_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notice",
            name="trigger_events",
        ),
    ]
